### ISSUE TITLE
Question: Why do we need QueryBus ? Queries its synchronous operations...

### ISSUE THREAD

**Issue by ddenysov** [somnambulist-tech/domain#4]
https://github.com/somnambulist-tech/domain/blob/759a91403cac41085456ae27816ba75b02bcc853/src/Queries/Adapters/MessengerQueryBus.php#L10

**Comment by dave-redfern** [comment]
@ddenysov It is to separate messages that should have a return from those that have no return from handling. Under-the-hood the default implementations use Symfony Messenger, and that makes no distinction between any kind of "message" object. You can send any message to any registered bus. These interfaces and default implementations ensure that specific types of message are only sent to specific buses. True: they can still be misconfigured, but at least code wise, you can only send events to the event bus, queries to the query bus etc.

Events, commands, and jobs are "fire and forget". They should not return anything. Raise exceptions maybe (in the case of commands, but not the others), but otherwise done. Events and jobs are inherently async so truly are fire and forget.

Queries on the other hand are questions into the system that inherently require a response after dispatch with the result. Symfony Messenger handles this by using a trait that can return the response from the message envelope and that is then returned to the calling code.

The main benefit of all of this is that it's all isolated and testable. You can even mock handling of a query or command in tests, or change the handler without having to change any of the calling code - provided the response is the same structure, it will all continue working. For example: you may move from pulling data from an ORM repository to an API. Only the handler has to change when using a query bus.

This is largely my own opinion, influenced by various reading around the subject.
